[package]
name = "rdm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
# anyhow = "1.0.86"
# tokio-util = { version = "0.7.11", features = ["codec"] }

[features]
default = ["rdm"]
rdm = []