[package]
name = "rdm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytes = "1.2.1"
thiserror = "1.0.37"
tokio-util = { version = "0.7.4", features = ["codec"] }